
/** List of Client */
export const GET_ROLE_LIST_REQUEST = 'GET_ROLE_LIST_REQUEST';
export const SET_ROLE_LIST_REQUEST = 'SET_ROLE_LIST_REQUEST';

//
export const CREATE_ROLE = 'CREATE_ROLE';
export const CREATE_ROLE_SUCCESS = 'CREATE_ROLE_SUCCESS';

