
/** List of Client */
export const GET_CLIENT_LIST_REQUEST = 'GET_CLIENT_LIST_REQUEST';
export const SET_CLIENT_LIST_REQUEST = 'SET_CLIENT_LIST_REQUEST';
//Add Client
export const CREATE_CLIENT = 'CREATE_CLIENT';
export const CREATE_CLIENT_SUCCESS = 'CREATE_CLIENT_SUCCESS';